# Generated by Django 5.2.7 on 2025-11-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
    ]
