"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gbrng&khmt)48ht5+b40%p*h#n0j2r-7jp9=2+%(jj$no0x049'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition


CUSTOM_APPS = [
    'home',
    'contact',
    'action',
    'join',
    'blog'
]

EXTERNAL_APPS = [
    
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

INSTALLED_APPS = DJANGO_APPS + EXTERNAL_APPS + CUSTOM_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# CONFIGURATION EMAIL INTELLIGENTE - FONCTIONNE EN DEV ET PROD
# ==============================================================================

import os
from django.core.exceptions import ImproperlyConfigured

import os

# Backend SMTP standard - fonctionne avec SendGrid et Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_TIMEOUT = 30
DEFAULT_FROM_EMAIL = 'deboutwanindara@gmail.com'
SERVER_EMAIL = DEFAULT_FROM_EMAIL

def get_email_config():
    """
    Récupère la configuration email - Supporte SendGrid (recommandé) et Gmail
    """
    # 1. Vérifier SendGrid en premier (recommandé pour étudiants - gratuit)
    try:
        from .email_config import SENDGRID_API_KEY
        if SENDGRID_API_KEY:
            # Configuration SendGrid
            return {
                'host': 'smtp.sendgrid.net',
                'port': 587,
                'use_tls': True,
                'use_ssl': False,
                'user': 'apikey',
                'password': SENDGRID_API_KEY,
                'provider': 'SendGrid'
            }
    except ImportError:
        pass
    
    # 2. Essayer Gmail avec App Password
    env_password = os.getenv('EMAIL_PASSWORD')
    if not env_password:
        try:
            from .email_config import EMAIL_PASSWORD
            env_password = EMAIL_PASSWORD
        except ImportError:
            pass
    
    if env_password:
        # Configuration Gmail
        return {
            'host': 'smtp.gmail.com',
            'port': 587,
            'use_tls': True,
            'use_ssl': False,
            'user': EMAIL_HOST_USER,
            'password': env_password,
            'provider': 'Gmail'
        }
    
    return None

email_config = get_email_config()

if email_config:
    # Appliquer la configuration
    EMAIL_HOST = email_config['host']
    EMAIL_PORT = email_config['port']
    EMAIL_USE_TLS = email_config['use_tls']
    EMAIL_USE_SSL = email_config['use_ssl']
    EMAIL_HOST_USER = email_config['user']
    EMAIL_HOST_PASSWORD = email_config['password']
    
    print(f"✅ Configuration email activée - {email_config['provider']}")
    print(f"✅ Serveur SMTP: {EMAIL_HOST}:{EMAIL_PORT}")
    if email_config['provider'] == 'SendGrid':
        print("✅ SendGrid détecté - Gratuit jusqu'à 100 emails/jour")
else:
    print("⚠️ ATTENTION: Aucune configuration email trouvée")
    print("⚠️ Configurez SendGrid (gratuit) ou Gmail dans core/email_config.py")
    print("📖 Consultez SETUP_SENDGRID_SIMPLE.md pour les instructions")
