# Generated by Django 5.2.7 on 2025-11-07 02:06

import join.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('motivation', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=join.models.photo_upload_to)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
