# Generated by Django 5.2.7 on 2025-11-07 02:40

import join.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='profession',
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ville de résidence'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='diploma',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Diplôme'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], default='O', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Langues parlées'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse mail'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=join.models.photo_upload_to, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.TextField(blank=True, default='', verbose_name='Compétences'),
        ),
    ]
