# Generated by Django 5.2.7 on 2025-11-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_remove_applicant_motivation_remove_applicant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.CharField(blank=True, choices=[('GIN', 'Guinée'), ('FRA', 'France'), ('USA', 'États-Unis'), ('CAN', 'Canada'), ('GBR', 'Royaume-Uni'), ('BEL', 'Belgique'), ('DEU', 'Allemagne'), ('ITA', 'Italie'), ('ESP', 'Espagne'), ('CHE', 'Suisse'), ('SEN', 'Sénégal'), ('CIV', "Côte d'Ivoire"), ('MLI', 'Mali'), ('MAR', 'Maroc'), ('AUTRE', 'Autre pays')], default='GIN', max_length=10, verbose_name='Pays de résidence'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, choices=[('CONAKRY', 'Conakry'), ('KAMSAR', 'Kamsar'), ('BOKE', 'Boké'), ('KINDIA', 'Kindia'), ('MAMOU', 'Mamou'), ('LABE', 'Labé'), ('KANKAN', 'Kankan'), ('NZEREKORE', "N'Zérékoré"), ('AUTRE', 'Autre ville')], default='CONAKRY', max_length=20, verbose_name='Ville de résidence'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='diploma',
            field=models.CharField(blank=True, choices=[('BAC', 'Baccalauréat'), ('BTS', 'Brevet de Technicien Supérieur (BTS)'), ('LIC', 'Licence'), ('MASTER', 'Master'), ('DOC', 'Doctorat'), ('DUT', 'DUT'), ('CAP', "Certificat d'Aptitude Professionnelle"), ('BEP', "Brevet d'Études Professionnelles"), ('AUTRE', 'Autre diplôme')], default='', max_length=10, verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='district',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='languages',
            field=models.CharField(blank=True, default='', help_text='Sélectionnez une ou plusieurs langues', max_length=200, verbose_name='Langues parlées'),
        ),
    ]
