# Generated by Django 5.2.7 on 2025-11-07 04:16

import join.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_applicant_country_alter_applicant_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('position', models.CharField(blank=True, default='', max_length=150, verbose_name='Poste')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone')),
                ('numero_id', models.CharField(max_length=50, unique=True, verbose_name='Numéro ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=join.models.photo_upload_to, verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
    ]
