# Generated by Django 5.2.7 on 2025-11-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_add_membre_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Photo')),
                ('category', models.CharField(choices=[('EVENTS', 'Événements'), ('TEAM', 'Équipe'), ('PROJECTS', 'Projets'), ('COMMUNITY', 'Communauté'), ('ACTIVITIES', 'Activités')], default='EVENTS', max_length=20)),
                ('date_taken', models.DateField(verbose_name='Date de prise de vue')),
                ('featured', models.BooleanField(default=False, verbose_name='Photo à la une')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo de galerie',
                'verbose_name_plural': 'Photos de galerie',
                'ordering': ['-date_taken', '-created_at'],
            },
        ),
    ]
